defaultBaseImage: cgr.dev/chainguard/static
defaultPlatforms:
- linux/arm64
- linux/amd64
- linux/arm/v7

builds:
- id: anubis
  main: ./cmd/anubis
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X github.com/bentemple/anubis.Version={{.Env.VERSION}}
